language: go
go:
- "1.12"
sudo: false
addons:
  postgresql: '9.5'
services:
- postgres
- docker
env:
  global:
  - GO111MODULE=on
  matrix:
  - LIBRDKAFKA_VERSION=v0.11.4
cache:
  directories:
  - "$HOME/.cache/librdkafka"
before_install:
- sudo /bin/bash ./travis.sh
before_script: make setup-ci
script: make test
